- angle: 0
  batch_size: 64
  burn_in: 1000
  channels: 3
  decay: 0.0005
  exposure: 1.5
  height: 320
  hue: 0.1
  learning_rate: 0.001
  max_batches: 500200
  momentum: 0.9
  policy: steps
  saturation: 1.5
  scales: 0.1, 0.1
  steps: 400000, 450000
  subdivision: 1
  type: net_info
  width: 320
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 32
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 64
  pad: 1
  stride: 2
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 32
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 64
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 128
  pad: 1
  stride: 2
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 64
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 128
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 64
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 128
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 2
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 2
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 2
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 512
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 512
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 512
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 512
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 1
  type: convolution
- activation: linear
  from: -3
  type: short_cut
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 512
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 512
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 512
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 1024
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 75
  pad: 0
  stride: 1
  type: convolution
- anchors: 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
  classes: 20
  ignore_thresh: 0.5
  jitter: 0.3
  mask: 6,7,8
  num: 9
  random: 1
  truth_thresh: 1
  type: yolo
- layers: -4
  type: route
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- stride: 2
  type: upsample
- layers: -1, 61
  type: route
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 256
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 512
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 75
  pad: 0
  stride: 1
  type: convolution
- anchors: 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
  classes: 20
  ignore_thresh: 0.5
  jitter: 0.3
  mask: 3,4,5
  num: 9
  random: 1
  truth_thresh: 1
  type: yolo
- layers: -4
  type: route
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- stride: 2
  type: upsample
- layers: -1, 36
  type: route
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 128
  pad: 0
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 3
  out_channels: 256
  pad: 1
  stride: 1
  type: convolution
- activation: leaky
  batch_normalize: 1
  kernel_size: 1
  out_channels: 75
  pad: 0
  stride: 1
  type: convolution
- anchors: 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
  classes: 20
  ignore_thresh: 0.5
  jitter: 0.3
  mask: 0,1,2
  num: 9
  random: 1
  truth_thresh: 1
  type: yolo
