- type: net_info
  batch_size: 64
  subdivision: 1
  width: 320
  height: 320
  channels: 3
  momentum: 0.9
  decay: 0.0005
  angle: 0
  saturation: 1.5
  exposure: 1.5
  hue: .1
  learning_rate: 0.001
  burn_in: 1000
  max_batches: 500200
  policy: steps
  steps: 400000, 450000
  scales: 0.1, 0.1

- type: convolution
  out_channels: 32
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 64
  kernel_size: 3
  stride: 2
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 32
  kernel_size: 1
  stride: 1
  pad: 0
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 64
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 3
  stride: 2
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 64
  kernel_size: 1
  stride: 1
  pad: 0
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 128
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 64
  kernel_size: 1
  stride: 1
  pad: 0
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 128
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 2
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 2
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 2
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 512
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 512
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear

- type: convolution
  out_channels: 512
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: short_cut
  from: -3
  activation: linear






- type: convolution
  out_channels: 512
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 1024
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 255
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: yolo
  mask: 6,7,8
  anchors: 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
  classes: 80
  num: 9
  jitter: 0.3
  ignore_thresh: 0.5
  truth_thresh: 1
  random: 1

- type: route
  layers: -4

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: upsample
  stride: 2

- type: route
  layers: -1, 61

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 512
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 255
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: yolo
  mask: 3,4,5
  anchors: 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
  classes: 80
  num: 9
  jitter: 0.3
  ignore_thresh: 0.5
  truth_thresh: 1
  random: 1

- type: route
  layers: -4

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: upsample
  stride: 2

- type: route
  layers: -1, 36

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 128
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 256
  kernel_size: 3
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: convolution
  out_channels: 255
  kernel_size: 1
  stride: 1
  pad: 1
  batch_normalize: 1
  activation: leaky

- type: yolo
  mask: 0,1,2
  anchors: 10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326
  classes: 80
  num: 9
  jitter: 0.3
  ignore_thresh: 0.5
  truth_thresh: 1
  random: 1


